### ISSUE TITLE
pipx installation incompatible with external lib dependencies in commands

### ISSUE THREAD

**Issue by ycouble** [Konubinix/click-project#11]
I don't know if it is an issue, but if I installed click-project through pipx, I cannot execute a command with dependencies that are not already embedded with pipx. 

E.G if I have a command that imports pandas, the command fails.

Is there a way to add a directory to the clk python path ? maybe in some parameters ?

**Comment by Konubinix** [comment]
Indeed, to take advantage of the features provided by click-project, the command needs to have the click-project packages available. Also, click-project basically imports the commands like it would import any other package.

Naively, it makes sense that both must be in the same virtualenvironment for this to work. Actually, this issue is the sign that pipx did well its job in the first place, meaning isolating the python runtime of the installation of click-project.

Yet, this seems like a sensible request. I guess we need to find a good way to make a command access third party libraries.

So far, I guess that we could add a way to install third party libraries where clk is installed, either by providing a function that the command would call
It would look like:
```python
from click_project.lib import install_package
install_package("pandas")
import pandas as pd
```
or 
```python
from click_project.lib import install_package
pd = install_package_import("pandas", pandas)
```
Otherwise, we could add a command in clk to access pip from inside the virtualenv, like `clk pip...`, this would allow `clk pip install pandas`

Most likely we could benefit from providing both :-P.

**Comment by Konubinix** [comment]
I've added the command `clk pip` that run the pip command inside the virtualenv of the installed clk.
When the 0.14.0 is out, you could try using it.

Actually, I would suggest otherwise: try to install click-project with `pipx install --system-site-packages click-project`
This will let clk have access to pandas installed outside of the venv. IMHO, it is the most elegant way of using click-project. Since most likely your commands will naturally depend on globally installed dependencies.

**Comment by Konubinix** [comment]
I updated the documentation to help people paliate this kind of issue. https://github.com/Konubinix/click-project#why-cannot-i-run-my-command-that-needs-library-x-that-is-installed-on-my-computer

I don't think of anything else to be done in the scope of this issue. So I am closing it now. Feel free to reopen it if you think the subject might need more attention.

Thanks for your report.
